<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="imu">
  <!-- imu -->
  <link name="imu">
    <visual>
      <geometry>
        <box size="${imu_box_size} ${imu_box_size} ${imu_box_size}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="red">
        <color rgba="1.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${imu_box_size} ${imu_box_size} ${imu_box_size}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </collision>
    <xacro:box_inertial_matrix m="${imu_mass}" l="${imu_box_size}" w="${imu_box_size}" h="${imu_box_size}" />
  </link>

  <!-- joint -->
  <joint name="imu_to_base_link" type="fixed">
    <parent link="base_link" />
    <child link="imu" />
    <origin xyz="-${base_box_size * 0.5 + imu_box_size * 0.5} 0.0 0.0" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <gazebo reference="imu">
    <material>Gazebo/Green</material>
  </gazebo>
</robot>