<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lidar">
  <!-- lidar -->
  <link name="arm">
    <visual>
      <geometry>
        <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="black">
        <color rgba="0.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_cylinder_radius}" length="${arm_cylinder_length}" />
      </geometry>
      <xacro:remove-collision />
    </collision>
    <xacro:cylinder_inertial_matrix m="${arm_mass}" r="${arm_cylinder_radius}" h="${arm_cylinder_length}" />
  </link>

  <!-- joint -->
  <joint name="arm_to_base_link" type="fixed">
    <parent link="base_link" />
    <child link="arm" />
    <origin xyz="0.0 0.0 ${base_box_size * 0.5 + arm_cylinder_length * 0.5}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <gazebo reference="arm">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- lidar -->
  <link name="lidar">
    <visual>
      <geometry>
        <cylinder radius="${lidar_cylinder_radius}" length="${lidar_cylinder_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="red">
        <color rgba="1.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_cylinder_radius}" length="${lidar_cylinder_length}" />
      </geometry>
      <xacro:remove-collision />
    </collision>
    <xacro:cylinder_inertial_matrix m="${lidar_mass}" r="${lidar_cylinder_radius}" h="${lidar_cylinder_length}" />
  </link>

  <!-- joint -->
  <joint name="lidar_to_arm" type="fixed">
    <parent link="arm" />
    <child link="lidar" />
    <origin xyz="0.0 0.0 ${arm_cylinder_length * 0.5 + lidar_cylinder_length * 0.5}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <gazebo reference="lidar">
    <material>Gazebo/Red</material>
  </gazebo>
</robot>