<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sim-robot">

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_box_size} ${base_box_size} ${base_box_size}" />
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_box_size} ${base_box_size} ${base_box_size}" />
      </geometry>
    </collision>
    <xacro:box_inertial_matrix m="${base_mass}" l="${base_box_size}" w="${base_box_size}" h="${base_box_size}" />
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- joint -->

  <joint name="base_to_link4" type="continuous">
    <parent link="link4" />
    <child link="base_link" />
    <origin xyz="${link4_length * 0.5 - base_box_size * 0.5} -${base_box_size * 0.5 + link4_width * 0.5} 0.0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <xacro:joint-dynamic />
  </joint>

  <xacro:include filename="lidar.xacro" />
  <xacro:include filename="imu.xacro" />
  <xacro:include filename="camera.xacro" />

  <xacro:include filename="sensor-laser.xacro" />
  <xacro:include filename="sensor-imu.xacro" />
  <xacro:include filename="sensor-camera.xacro" />

</robot>