<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheels">
  <!-- wheels -->


  <xacro:macro name="add_wheel" params="name flag">
    <link name="${name}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_cylinder_radius}" length="${wheel_cylinder_length}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${PI * 0.5} 0.0 0.0" />
        <material name="black">
          <color rgba="0.0 0.0 0.0 ${transparency}" />
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_cylinder_radius}" length="${wheel_cylinder_length}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${PI * 0.5} 0.0 0.0" />
      </collision>
      <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_cylinder_radius}" h="${wheel_cylinder_length}" />
    </link>

    <!-- joint -->
    <joint name="${name}_wheel_to_base_link" type="continuous">
      <parent link="base_link" />
      <child link="${name}_wheel" />
      <origin xyz="0.0 ${flag * base_box_size * 0.5} -${base_box_size * 0.5 + ground_clearance - wheel_cylinder_radius}"/>
      <axis xyz="0 1 0" />
    </joint>

    <gazebo reference="${name}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <xacro:add_wheel name="left" flag="1" />
  <xacro:add_wheel name="right" flag="-1" />

  <xacro:macro name="add_support_wheel" params="name flag">
    <link name="${name}_support_wheel">
      <visual>
        <geometry>
          <sphere radius="${ground_clearance * 0.5}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <material name="black">
          <color rgba="0.0 0.0 0.0 ${transparency}" />
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${ground_clearance * 0.5}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </collision>
      <xacro:sphere_inertial_matrix m="${support_wheel_mass}" r="${ground_clearance * 0.5}" />
    </link>

    <!-- joint -->
    <joint name="${name}_support_wheel_to_base_link" type="continuous">
      <parent link="base_link" />
      <child link="${name}_support_wheel" />
      <origin xyz="${flag * (base_box_size * 0.5 - ground_clearance * 0.5)} 0.0 -${base_box_size * 0.5 + ground_clearance * 0.5}"/>
      <axis xyz="1 1 1" />
    </joint>

    <gazebo reference="${name}_support_wheel">
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <xacro:add_support_wheel name="front" flag="1" />
  <xacro:add_support_wheel name="back" flag="-1" />


</robot>