<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sim-robot">
  <xacro:property name="foot_box_size" value="0.001" />
  <xacro:property name="base_box_size" value="0.3" />
  <xacro:property name="imu_box_size" value="0.1" />
  <xacro:property name="lidar_cylinder_radius" value="0.08" />
  <xacro:property name="lidar_cylinder_length" value="0.1" />
  <xacro:property name="camera_cylinder_radius" value="0.05" />
  <xacro:property name="camera_cylinder_length" value="0.05" />
  <xacro:property name="transparency" value="0.8" />
  <xacro:property name="PI" value="3.1415926535" />

  <!-- foot base link -->
  <link name="base_footprint">
    <visual>
      <geometry>
        <box size="${foot_box_size} ${foot_box_size} ${foot_box_size}" />
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
  </link>

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_box_size} ${base_box_size} ${base_box_size}" />
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 ${transparency}" />
      </material>
    </visual>
  </link>

  <!-- joint -->
  <joint name="base_to_foot" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0.0 0.0 ${base_box_size * 0.5}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <!-- lidar -->
  <link name="lidar">
    <visual>
      <geometry>
        <cylinder radius="${lidar_cylinder_radius}" length="${lidar_cylinder_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="red">
        <color rgba="1.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
  </link>

  <!-- joint -->
  <joint name="lidar_to_base_link" type="fixed">
    <parent link="base_link" />
    <child link="lidar" />
    <origin xyz="0.0 0.0 ${base_box_size * 0.5 + lidar_cylinder_length * 0.5}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <!-- imu -->
  <link name="imu">
    <visual>
      <geometry>
        <box size="${imu_box_size} ${imu_box_size} ${imu_box_size}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="green">
        <color rgba="0.0 1.0 0.0 ${transparency}" />
      </material>
    </visual>
  </link>

  <!-- joint -->
  <joint name="imu_to_base_link" type="fixed">
    <parent link="base_link" />
    <child link="imu" />
    <origin xyz="${base_box_size * 0.5 + imu_box_size * 0.5} 0.0 0.0" rpy="${PI} 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <!-- camera -->
  <link name="camera">
    <visual>
      <geometry>
        <cylinder radius="${camera_cylinder_radius}" length="${camera_cylinder_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="blue">
        <color rgba="0.0 0.0 1.0 ${transparency}" />
      </material>
    </visual>
  </link>

  <!-- joint -->
  <joint name="camera_to_base_link" type="fixed">
    <parent link="base_link" />
    <child link="camera" />
    <origin xyz="0.0 ${base_box_size * 0.5 + camera_cylinder_length * 0.5} 0.0" rpy="${-PI * 0.5} 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

</robot>