<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sim-robot">
  <xacro:property name="foot_box_size" value="0.001" />
  <xacro:property name="base_box_size" value="0.3" />
  <xacro:property name="imu_box_size" value="0.1" />
  <xacro:property name="lidar_cylinder_radius" value="0.08" />
  <xacro:property name="lidar_cylinder_length" value="0.1" />
  <xacro:property name="camera_cylinder_radius" value="0.05" />
  <xacro:property name="camera_cylinder_length" value="0.05" />
  <xacro:property name="transparency" value="0.8" />
  <xacro:property name="PI" value="3.1415926535" />
  <xacro:property name="foot_mass" value="0.001" />
  <xacro:property name="base_mass" value="20.0" />
  <xacro:property name="lidar_mass" value="5.0" />
  <xacro:property name="imu_mass" value="1.0" />
  <xacro:property name="camera_mass" value="1.0" />

  <xacro:include filename="util.xacro" />

  <!-- foot base link -->
  <link name="base_footprint">
    <visual>
      <geometry>
        <box size="${foot_box_size} ${foot_box_size} ${foot_box_size}" />
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${foot_box_size} ${foot_box_size} ${foot_box_size}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </collision>
  </link>

  <gazebo reference="base_footprint">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_box_size} ${base_box_size} ${base_box_size}" />
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 ${transparency}" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_box_size} ${base_box_size} ${base_box_size}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </collision>
    <xacro:box_inertial_matrix m="${base_mass}" l="${base_box_size}" w="${base_box_size}" h="${base_box_size}" />
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- joint -->
  <joint name="base_to_foot" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0.0 0.0 ${base_box_size * 0.5}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
  </joint>

  <xacro:include filename="lidar.xacro" />
  <xacro:include filename="imu.xacro" />
  <xacro:include filename="camera.xacro" />

  <xacro:include filename="sensor-laser.xacro" />

</robot>